name: Build Dapp
on:
  push:
    branches:
      - alpha
      - beta
      - alpha

jobs:
  check:
    name: Build Dapp, ready to be deployed
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Cache pnpm modules
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: pnpm-modules-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Install pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.30.0
          run_install: true

      - name: Build Dapp
        run: pnpm run build-dapp
        env:
          ENVIR: PROD
          NODE_DEBUG: false
          INFURA_API_KEY: ${{ secrets.INFURA_API_KEY }}
          COVALENT_API_KEY: ${{ secrets.COVALENT_API_KEY }}
          NFT_STORAGE_KEY: ${{ secrets.NFT_STORAGE_KEY }}

      - name: Delete .gitignore to include dapp/build in commit
        run: rm dapp/.gitignore

      - name: Commit Dapp build
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add web/dapp
          git commit -am "${{ github.ref_name }} dapp build !"

      - name: Push Dapp build
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: build/${{ github.ref_name }}
          force: true
          directory: "web/dapp"
